import { defineIndex } from 'twenty-sdk/define';

import {
  TELEGRAM_DELIVERY_AUDIT_DELIVERY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_DELIVERY_AUDIT_EXPECTED_UNKNOWN_AT_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_DELIVERY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_UNIVERSAL_IDENTIFIER,
  TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_UNKNOWN_AT_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_DELIVERY_AUDIT_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/modules/telegram/telegram-persistence-identifiers';

// Exactly one reset authorization may exist for an ambiguous delivery
// generation, even when callers race with different request IDs.
export default defineIndex({
  universalIdentifier:
    TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier:
    TELEGRAM_DELIVERY_AUDIT_OBJECT_UNIVERSAL_IDENTIFIER,
  isUnique: true,
  fields: [
    {
      universalIdentifier:
        TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_DELIVERY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        TELEGRAM_DELIVERY_AUDIT_DELIVERY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        TELEGRAM_DELIVERY_AUDIT_GENERATION_INDEX_UNKNOWN_AT_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        TELEGRAM_DELIVERY_AUDIT_EXPECTED_UNKNOWN_AT_FIELD_UNIVERSAL_IDENTIFIER,
    },
  ],
});
