import { defineObject, FieldType, MetadataWritability } from 'twenty-sdk/define';
import * as ids from 'src/modules/experience/experience-identifiers';

export default defineObject({
  universalIdentifier: ids.OUTREACHFOLLOWUP_OBJECT_ID,
  nameSingular: 'outreachFollowUp',
  namePlural: 'outreachFollowUps',
  labelSingular: 'Follow-up check',
  labelPlural: 'Follow-ups',
  icon: 'IconCalendarClock',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: ids.OUTREACHFOLLOWUP_NAME_ID,
  fields: [
    {
      universalIdentifier: ids.OUTREACHFOLLOWUP_NAME_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Follow-up',
      icon: 'IconAbc',
      defaultValue: "''",
    },
    {
      universalIdentifier: ids.FOLLOW_UP_DUEAT_ID,
      type: FieldType.DATE_TIME,
      name: 'dueAt',
      label: 'Due at',
      icon: 'IconCalendarClock',
      isNullable: true,
    },
    {
      universalIdentifier: ids.FOLLOW_UP_SCHEDULEDAT_ID,
      type: FieldType.DATE_TIME,
      name: 'scheduledAt',
      isUIEditable: false,
      writability: MetadataWritability.APPLICATION,
      label: 'Scheduled at',
      icon: 'IconCalendarClock',
      isNullable: true,
    },
    {
      universalIdentifier: ids.FOLLOW_UP_OCCURRENCEKEY_ID,
      type: FieldType.TEXT,
      name: 'occurrenceKey',
      isUIEditable: false,
      writability: MetadataWritability.APPLICATION,
      label: 'Occurrence key',
      icon: 'IconCalendarClock',
      isNullable: true,
    },
    {
      universalIdentifier: ids.FOLLOW_UP_VALIDATIONMESSAGE_ID,
      type: FieldType.TEXT,
      name: 'validationMessage',
      label: 'Follow-up check',
      icon: 'IconCalendarClock',
      isNullable: true,
    },
    {
      universalIdentifier: ids.FOLLOW_UP_STATUS_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'OPEN'",
      options: [
        {
          id: '5f55c05f-6bbb-5c4f-8fc0-c5a8d7cda08c',
          value: 'OPEN',
          label: 'Open',
          position: 0,
          color: 'blue',
        },
        {
          id: '8c886538-4a50-582e-921e-38f5411a7a76',
          value: 'COMPLETED',
          label: 'Completed',
          position: 1,
          color: 'green',
        },
        {
          id: 'f7942b7b-1e88-559b-b370-b5aca876caff',
          value: 'CANCELLED',
          label: 'Cancelled',
          position: 2,
          color: 'gray',
        },
      ],
    },
  ],
});
